sonar.projectKey=EnsyInc_Enclave.Web
sonar.organization=ensyinc
sonar.projectName=Enclave.Web

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,.angular/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/enclave-web/lcov.info
